// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh-mXvAJJDmN7pxcS3jsjdhDDWUeYuhUA',
    appId: '1:890406771583:web:91f5c0d97b2231dd75184a',
    messagingSenderId: '890406771583',
    projectId: 'hive-cec6e',
    authDomain: 'hive-cec6e.firebaseapp.com',
    storageBucket: 'hive-cec6e.firebasestorage.app',
    measurementId: 'G-QBS0SYLD83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKFOPZlY5zpOBit-LL9jP1ssWBKeO_42s',
    appId: '1:890406771583:android:25cfb9d7d3f36a7f75184a',
    messagingSenderId: '890406771583',
    projectId: 'hive-cec6e',
    storageBucket: 'hive-cec6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR6KRPR5eUnr3fBLcxKyAItS093QCYgH8',
    appId: '1:890406771583:ios:c7a2a19e50bdf63b75184a',
    messagingSenderId: '890406771583',
    projectId: 'hive-cec6e',
    storageBucket: 'hive-cec6e.firebasestorage.app',
    iosBundleId: 'com.example.demoUcs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR6KRPR5eUnr3fBLcxKyAItS093QCYgH8',
    appId: '1:890406771583:ios:c7a2a19e50bdf63b75184a',
    messagingSenderId: '890406771583',
    projectId: 'hive-cec6e',
    storageBucket: 'hive-cec6e.firebasestorage.app',
    iosBundleId: 'com.example.demoUcs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh-mXvAJJDmN7pxcS3jsjdhDDWUeYuhUA',
    appId: '1:890406771583:web:8cf42097ab6bcb1275184a',
    messagingSenderId: '890406771583',
    projectId: 'hive-cec6e',
    authDomain: 'hive-cec6e.firebaseapp.com',
    storageBucket: 'hive-cec6e.firebasestorage.app',
    measurementId: 'G-VECCN3TJGW',
  );
}
